module.exports = [
  {
    code:'USRS-LIST',title:'Users — List Page',cases:[
      {id:'UL-001',name:'User list loads with name, email, role, org, status, last login',pre:'Logged in as super_admin; users exist',steps:'1. Click Users in sidebar\n2. Observe table columns',expected:'Table: avatar, full name, email, role badge, org, status, last login, actions',priority:'Critical',type:'Positive'},
      {id:'UL-002',name:'Search users by email — full match',pre:'Users list',steps:'1. Enter exact email in search',expected:'That user row shown',priority:'High',type:'Positive'},
      {id:'UL-003',name:'Search users by name — partial',pre:'Users list',steps:'1. Enter partial first name',expected:'All matching users shown',priority:'High',type:'Positive'},
      {id:'UL-004',name:'Filter users by role — learner',pre:'Users list; mixed roles',steps:'1. Select "Learner" from role filter',expected:'Only learners shown',priority:'High',type:'Positive'},
      {id:'UL-005',name:'Filter users by role — instructor',pre:'Users list',steps:'1. Select "Instructor" filter',expected:'Only instructors shown',priority:'High',type:'Positive'},
      {id:'UL-006',name:'Filter users by role — org_admin',pre:'Users list',steps:'1. Select "Org Admin"',expected:'Only org admins shown',priority:'High',type:'Positive'},
      {id:'UL-007',name:'Filter users by status — Active',pre:'Users list; some inactive',steps:'1. Select "Active" status filter',expected:'Only active users shown',priority:'High',type:'Positive'},
      {id:'UL-008',name:'Filter users by org',pre:'Super_admin; multiple orgs',steps:'1. Select specific org in filter',expected:'Only users in that org shown',priority:'High',type:'Positive'},
      {id:'UL-009',name:'Filter users by division',pre:'Users list',steps:'1. Select division filter',expected:'Only users in that division shown',priority:'Medium',type:'Positive'},
      {id:'UL-010',name:'Combine role and org filters',pre:'Users list',steps:'1. Filter by role=instructor AND org=Acme',expected:'Only instructors in Acme org shown',priority:'Medium',type:'Positive'},
      {id:'UL-011',name:'Sort users by last login date',pre:'Users list',steps:'1. Click Last Login column header',expected:'Users sorted with most recently active first',priority:'Medium',type:'Positive'},
      {id:'UL-012',name:'Sort users by name A-Z',pre:'Users list',steps:'1. Click Name column',expected:'Alphabetical order',priority:'Low',type:'Positive'},
      {id:'UL-013',name:'Pagination shows correct page and total count',pre:'More than page limit users',steps:'1. View pagination controls',expected:'"Showing 1–25 of 340" or similar; next/prev buttons work',priority:'Medium',type:'Positive'},
      {id:'UL-014',name:'Bulk activate selected users',pre:'Some inactive users selected',steps:'1. Select 5 inactive users\n2. Bulk Activate\n3. Confirm',expected:'5 users activated; status badge updates; success toast with count',priority:'High',type:'Positive'},
      {id:'UL-015',name:'Bulk deactivate users',pre:'Active users selected',steps:'1. Select users\n2. Bulk Deactivate\n3. Confirm',expected:'Users deactivated; cannot log in until reactivated',priority:'High',type:'Positive'},
      {id:'UL-016',name:'Bulk export users as CSV',pre:'Users selected or all selected',steps:'1. Select all\n2. Export CSV',expected:'CSV: name, email, role, org, division, status, last login, created date',priority:'High',type:'Positive'},
      {id:'UL-017',name:'Bulk delete with strong confirmation required',pre:'Users selected',steps:'1. Select users\n2. Bulk Delete\n3. Check confirmation requirement',expected:'Confirmation requires typing "DELETE" or similar; not just single click',priority:'High',type:'UI/UX'},
      {id:'UL-018',name:'Org_admin sees only own org users',pre:'Logged in as org_admin',steps:'1. Open Users list',expected:'Only users in own org visible; no cross-org data',priority:'Critical',type:'Security'},
      {id:'UL-019',name:'User list empty state for new org',pre:'Org with no users',steps:'1. Filter by new org',expected:'"No users found" with Invite button',priority:'Low',type:'Negative'},
      {id:'UL-020',name:'User list responsive at 1280px',pre:'Viewport 1280px',steps:'1. View users list',expected:'All columns legible; no overflow; horizontal scroll only in table container if needed',priority:'Medium',type:'UI/UX'},
    ]
  },
  {
    code:'USRS-DETAIL',title:'Users — User Detail Page',cases:[
      {id:'UD-001',name:'User detail page opens with tabs: Profile, Courses, Activity, Permissions, Rewards',pre:'Click user from list',steps:'1. Click user name/row\n2. Observe page structure',expected:'Detail page with tab navigation: Profile, Courses Enrolled, Activity Log, Permissions, Rewards/Points',priority:'Critical',type:'Positive'},
      {id:'UD-002',name:'Profile tab shows all user data fields',pre:'User detail; Profile tab',steps:'1. View Profile tab',expected:'Name, email, avatar, bio, phone, org, division, role, status, created date, last login all visible',priority:'High',type:'Positive'},
      {id:'UD-003',name:'Edit user — change first/last name',pre:'Profile tab; edit mode',steps:'1. Click Edit\n2. Change name\n3. Save',expected:'Name updated; list and header reflect change',priority:'High',type:'Positive'},
      {id:'UD-004',name:'Edit user — change email',pre:'Edit mode',steps:'1. Change email to new valid address\n2. Save',expected:'Email updated; user should re-verify if email verification is required',priority:'High',type:'Positive'},
      {id:'UD-005',name:'Edit user — duplicate email rejected',pre:'Edit mode; email taken by another user',steps:'1. Enter another user\'s email\n2. Save',expected:'Error: "Email already registered to another account"',priority:'Critical',type:'Validation'},
      {id:'UD-006',name:'Edit user — invalid email format rejected',pre:'Edit mode',steps:'1. Enter "notvalid@"\n2. Save',expected:'Validation error: invalid email',priority:'High',type:'Validation'},
      {id:'UD-007',name:'Change user role from learner to instructor',pre:'Edit mode; role dropdown',steps:'1. Change role to "Instructor"\n2. Save',expected:'Role updated; user gets instructor permissions; role badge updates',priority:'High',type:'Positive'},
      {id:'UD-008',name:'Activate deactivated user account',pre:'User is inactive',steps:'1. Click "Activate Account"\n2. Confirm',expected:'Status changed to Active; user can log in',priority:'High',type:'Positive'},
      {id:'UD-009',name:'Deactivate active user account',pre:'User is active',steps:'1. Click "Deactivate Account"\n2. Confirm',expected:'User deactivated; active sessions invalidated; cannot log in until reactivated',priority:'High',type:'Positive'},
      {id:'UD-010',name:'Deactivated user existing sessions are invalidated',pre:'User active and logged in; then deactivated',steps:'1. Deactivate user\n2. User makes an API call with existing token',expected:'401 Unauthorized; session invalidated immediately',priority:'Critical',type:'Security'},
      {id:'UD-011',name:'Change user password as admin',pre:'Edit mode; password section',steps:'1. Enter new password (meets policy)\n2. Save',expected:'Password changed; user must use new password; old sessions optionally invalidated',priority:'High',type:'Positive'},
      {id:'UD-012',name:'Admin-set password too short fails',pre:'Edit mode; password field',steps:'1. Enter 5-char password\n2. Save',expected:'Validation error per password policy',priority:'High',type:'Validation'},
      {id:'UD-013',name:'Send password reset email to user',pre:'User detail; Profile tab',steps:'1. Click "Send Password Reset"\n2. Confirm',expected:'Password reset email sent to user; success toast',priority:'High',type:'Positive'},
      {id:'UD-014',name:'Delete user — permanent deletion with strong confirm',pre:'User detail',steps:'1. Click Delete User\n2. Type username to confirm\n3. Delete',expected:'User deleted; all enrollments, completions, and data removed or anonymized',priority:'High',type:'Positive'},
      {id:'UD-015',name:'Cannot delete user who is only org_admin',pre:'User is sole org_admin',steps:'1. Try to delete user',expected:'Error: "Cannot delete the only admin of an organisation. Assign another admin first."',priority:'High',type:'Negative'},
      {id:'UD-016',name:'Upload user avatar image',pre:'Profile edit mode',steps:'1. Upload valid JPEG avatar\n2. Save',expected:'Avatar updated; shown in list and detail header',priority:'Medium',type:'Positive'},
      {id:'UD-017',name:'Avatar file too large rejected',pre:'Profile edit mode',steps:'1. Upload 10MB image as avatar',expected:'Error: file too large',priority:'Medium',type:'Validation'},
      {id:'UD-018',name:'IDOR — user cannot edit another user\'s profile via API',pre:'Regular user logged in',steps:'1. PUT /api/users/{other_user_id} with own token',expected:'403 Forbidden',priority:'Critical',type:'Security'},
    ]
  },
  {
    code:'USRS-CRSES',title:'Users — Courses & Progress Tab',cases:[
      {id:'UC-001',name:'Courses tab shows all courses user is enrolled in',pre:'User detail; Courses tab; user has enrollments',steps:'1. Click Courses tab on user detail',expected:'Table: course name, enrolled date, last accessed, progress %, completion status',priority:'Critical',type:'Positive'},
      {id:'UC-002',name:'Progress bar reflects actual completion percentage',pre:'User completed 3/5 lessons',steps:'1. View Courses tab',expected:'Progress bar at 60%; matches backend progress data',priority:'High',type:'Positive'},
      {id:'UC-003',name:'Completed courses show completion date and certificate badge',pre:'User completed a course',steps:'1. View Courses tab',expected:'"Completed" badge, completion date, and Certificate link shown',priority:'High',type:'Positive'},
      {id:'UC-004',name:'Manually enroll user in a course from user detail',pre:'Courses tab; user not enrolled in course X',steps:'1. Click "Enroll in Course"\n2. Search and select course\n3. Confirm',expected:'User enrolled in course; course appears in list with 0% progress',priority:'High',type:'Positive'},
      {id:'UC-005',name:'Enroll user in course they\'re already in — rejected',pre:'User already enrolled',steps:'1. Try to enroll in same course',expected:'Error: "User is already enrolled in this course"',priority:'High',type:'Validation'},
      {id:'UC-006',name:'Unenroll user from course with confirmation',pre:'User enrolled in course',steps:'1. Click Unenroll on a course\n2. Confirm',expected:'User unenrolled; progress data optionally retained or deleted per setting',priority:'High',type:'Positive'},
      {id:'UC-007',name:'Reset user progress in a course',pre:'User has progress; Reset button',steps:'1. Click Reset Progress on a course\n2. Confirm',expected:'Progress reset to 0%; completion status cleared; user can re-attempt',priority:'Medium',type:'Positive'},
      {id:'UC-008',name:'Grant manual course completion',pre:'Courses tab; progress below 100%',steps:'1. Click "Mark Complete" on a course\n2. Confirm',expected:'Course marked complete; certificate issued if auto-certificate configured',priority:'High',type:'Positive'},
      {id:'UC-009',name:'Filter user courses by status — In Progress',pre:'Courses tab; multiple status courses',steps:'1. Filter by "In Progress"',expected:'Only in-progress courses shown',priority:'Medium',type:'Positive'},
      {id:'UC-010',name:'Filter user courses by status — Completed',pre:'Courses tab',steps:'1. Filter by "Completed"',expected:'Only completed courses shown',priority:'Medium',type:'Positive'},
      {id:'UC-011',name:'View user certificate from Courses tab',pre:'User completed course with certificate',steps:'1. Click certificate link in Courses tab',expected:'Certificate PDF or preview opens',priority:'Medium',type:'Positive'},
      {id:'UC-012',name:'Courses tab shows empty state if no enrollments',pre:'User with no enrollments',steps:'1. Open Courses tab',expected:'"Not enrolled in any courses yet" with Enroll button',priority:'Low',type:'Negative'},
    ]
  },
  {
    code:'USRS-ACTVT',title:'Users — Activity & Permissions Tabs',cases:[
      {id:'UA-001',name:'Activity tab shows login history with IP and device',pre:'User detail; Activity tab',steps:'1. Click Activity tab',expected:'Login history: timestamp, IP address, browser/device, location (if available)',priority:'High',type:'Positive'},
      {id:'UA-002',name:'Activity tab shows content access events',pre:'User has viewed lessons',steps:'1. View Activity tab',expected:'Events: "Accessed Lesson X", "Submitted Quiz Y", "Downloaded Certificate Z" with timestamps',priority:'High',type:'Positive'},
      {id:'UA-003',name:'Activity tab shows admin action events for admin users',pre:'User is org_admin; has made changes',steps:'1. View Activity tab',expected:'Admin events: "Created course", "Deactivated user", "Changed settings" logged',priority:'High',type:'Positive'},
      {id:'UA-004',name:'Activity tab — filter by event type',pre:'Activity tab; multiple event types',steps:'1. Select "Login" from event type filter',expected:'Only login events shown',priority:'Medium',type:'Positive'},
      {id:'UA-005',name:'Activity tab — filter by date range',pre:'Activity tab',steps:'1. Set date range to last 7 days',expected:'Only events from last 7 days shown',priority:'Medium',type:'Positive'},
      {id:'UA-006',name:'Activity tab — export as CSV for audit',pre:'Activity tab',steps:'1. Click Export',expected:'CSV with event type, timestamp, IP, details downloaded',priority:'High',type:'Positive'},
      {id:'UA-007',name:'Activity tab — empty state for new user with no activity',pre:'Newly created user',steps:'1. Open Activity tab',expected:'"No activity recorded yet" message',priority:'Low',type:'Negative'},
      {id:'UA-008',name:'Permissions tab shows all explicit permission overrides for user',pre:'User detail; Permissions tab',steps:'1. Click Permissions tab',expected:'List of explicit permission assignments beyond role defaults (if any)',priority:'High',type:'Positive'},
      {id:'UA-009',name:'Grant user extra permission beyond their role',pre:'Permissions tab; user is learner',steps:'1. Add permission "Can create courses"\n2. Save',expected:'User now has course creation permission despite learner role',priority:'High',type:'Positive'},
      {id:'UA-010',name:'Revoke a permission granted to user',pre:'User has explicit permission',steps:'1. Remove the permission\n2. Save',expected:'Permission revoked; falls back to role default',priority:'High',type:'Positive'},
      {id:'UA-011',name:'Permissions tab shows inherited role permissions (read-only)',pre:'Permissions tab',steps:'1. View inherited permissions section',expected:'Role-based permissions listed as read-only; only overrides are editable here',priority:'Medium',type:'Positive'},
      {id:'UA-012',name:'Org_admin cannot grant super_admin-level permissions to any user',pre:'Logged in as org_admin',steps:'1. Try to grant super_admin permission to user',expected:'Super_admin level permissions not listed or blocked',priority:'Critical',type:'Security'},
    ]
  },
];
