module.exports = [
  {
    code:'ORGS-LIST',title:'Organisations — List Page',cases:[
      {id:'OL-001',name:'Orgs list loads with name, logo, status, user count, division count',pre:'Logged in as super_admin; orgs exist',steps:'1. Click Organizations in sidebar\n2. Observe columns',expected:'Table/card shows: logo thumbnail, org name, status badge, user count, division count, created date, actions',priority:'Critical',type:'Positive'},
      {id:'OL-002',name:'Search by org name — partial match',pre:'Multiple orgs',steps:'1. Type partial name in search\n2. Observe',expected:'Only matching orgs shown; others hidden',priority:'High',type:'Positive'},
      {id:'OL-003',name:'Search clears on X icon click to show all orgs',pre:'Search active',steps:'1. Click clear/X on search box',expected:'Full org list restored',priority:'Medium',type:'Positive'},
      {id:'OL-004',name:'Search with no matches shows empty state',pre:'Orgs list',steps:'1. Search "ZZZNONE999"',expected:'"No organisations found" empty state; no crash',priority:'Medium',type:'Negative'},
      {id:'OL-005',name:'Filter by status — Active only',pre:'Active and inactive orgs',steps:'1. Select "Active" from status filter',expected:'Only active orgs listed; inactive hidden',priority:'High',type:'Positive'},
      {id:'OL-006',name:'Filter by status — Inactive only',pre:'Mixed status orgs',steps:'1. Select "Inactive"',expected:'Only inactive orgs listed',priority:'High',type:'Positive'},
      {id:'OL-007',name:'Sort orgs by name A-Z',pre:'Orgs list',steps:'1. Click Name column header or select A-Z sort',expected:'Alphabetical order ascending',priority:'Medium',type:'Positive'},
      {id:'OL-008',name:'Sort orgs by created date newest first',pre:'Orgs list',steps:'1. Select Date sort',expected:'Most recently created org at top',priority:'Medium',type:'Positive'},
      {id:'OL-009',name:'Sort orgs by user count descending',pre:'Orgs with different user counts',steps:'1. Click Users column header',expected:'Org with most users at top',priority:'Low',type:'Positive'},
      {id:'OL-010',name:'Pagination — next page loads different orgs',pre:'More orgs than page size',steps:'1. Click Next page',expected:'Next set of orgs loads; page indicator updates',priority:'Medium',type:'Positive'},
      {id:'OL-011',name:'Page size selector changes rows shown',pre:'Orgs list with pagination',steps:'1. Change page size from 10 to 25',expected:'Up to 25 orgs shown per page',priority:'Low',type:'Positive'},
      {id:'OL-012',name:'Grid view shows org cards with logo',pre:'Orgs list; grid toggle available',steps:'1. Switch to Grid view',expected:'Cards shown with org logo, name, status pill; no table',priority:'Medium',type:'UI/UX'},
      {id:'OL-013',name:'List view shows org table with all columns',pre:'Orgs list; list toggle',steps:'1. Switch to List view',expected:'Table with all columns; sortable headers',priority:'Medium',type:'UI/UX'},
      {id:'OL-014',name:'Org list is responsive on 1024px tablet',pre:'Viewport 1024×768',steps:'1. Open Orgs list at 1024px\n2. Check layout',expected:'Table or cards display correctly; no horizontal scroll on row data',priority:'Medium',type:'UI/UX'},
      {id:'OL-015',name:'Org list skeleton loader shown while data fetches',pre:'Slow network (throttle)',steps:'1. Throttle to Slow 3G\n2. Open Orgs list',expected:'Skeleton/shimmer rows shown while loading; not blank white screen',priority:'Medium',type:'UI/UX'},
      {id:'OL-016',name:'Org_admin sees only their own org in list',pre:'Logged in as org_admin',steps:'1. Open Organizations page',expected:'Only own org visible; other orgs not listed',priority:'Critical',type:'Security'},
      {id:'OL-017',name:'Bulk select all and deactivate',pre:'Multiple active orgs; super_admin',steps:'1. Check select-all\n2. Choose "Deactivate" bulk action\n3. Confirm',expected:'All selected orgs deactivated; success toast',priority:'High',type:'Positive'},
      {id:'OL-018',name:'Bulk export org list as CSV',pre:'Select all orgs',steps:'1. Select all\n2. Export CSV\n3. Download',expected:'CSV with org name, status, user count, created date',priority:'Medium',type:'Positive'},
      {id:'OL-019',name:'Bulk action with zero selection shows error',pre:'No orgs checked',steps:'1. Click bulk action button',expected:'"Select at least one organisation" error',priority:'Medium',type:'Validation'},
      {id:'OL-020',name:'Click org row opens org detail page',pre:'Org in list',steps:'1. Click org name or row',expected:'Org detail page opens with tabs: Info, Members, Courses, Divisions, Settings, Analytics',priority:'High',type:'Positive'},
    ]
  },
  {
    code:'ORGS-FORM',title:'Organisations — Create & Edit Form',cases:[
      {id:'OF-001',name:'Create org form opens with all required fields visible',pre:'On Orgs list; click Create',steps:'1. Click "Create Organisation"\n2. Observe form',expected:'Fields: Name, Subdomain/Slug, Description, Logo, Status, Contact Email, Plan',priority:'High',type:'UI/UX'},
      {id:'OF-002',name:'Create org — all required fields filled, saves successfully',pre:'Create form open',steps:'1. Enter name "Acme Corp"\n2. Enter unique subdomain "acme"\n3. Add description\n4. Set status Active\n5. Click Save',expected:'Org created; redirected to org detail; success toast',priority:'Critical',type:'Positive'},
      {id:'OF-003',name:'Create org — name required field blank fails',pre:'Create form',steps:'1. Leave Name blank\n2. Save',expected:'Required field error on Name',priority:'Critical',type:'Validation'},
      {id:'OF-004',name:'Create org — subdomain required if configured as required',pre:'Create form',steps:'1. Leave subdomain blank\n2. Save',expected:'Required field error on subdomain (if required)',priority:'High',type:'Validation'},
      {id:'OF-005',name:'Create org — duplicate name rejected',pre:'Org "Acme Corp" exists',steps:'1. Enter name "Acme Corp"\n2. Save',expected:'Error: "Organisation with this name already exists"',priority:'High',type:'Validation'},
      {id:'OF-006',name:'Create org — duplicate subdomain rejected',pre:'Subdomain "acme" taken',steps:'1. Enter subdomain "acme"\n2. Save',expected:'Error: "This subdomain is already in use"',priority:'High',type:'Validation'},
      {id:'OF-007',name:'Subdomain with spaces or special chars rejected',pre:'Create form',steps:'1. Enter "my org!" as subdomain\n2. Save',expected:'Error: subdomain must be lowercase alphanumeric with hyphens only',priority:'High',type:'Validation'},
      {id:'OF-008',name:'Name max length 255 chars accepted',pre:'Create form',steps:'1. Enter 255-char name\n2. Save',expected:'Saved successfully',priority:'Low',type:'Boundary'},
      {id:'OF-009',name:'Name 256 chars rejected',pre:'Create form',steps:'1. Enter 256-char name\n2. Save',expected:'Validation error or input capped',priority:'Low',type:'Boundary'},
      {id:'OF-010',name:'Logo upload — valid PNG < 2MB accepted',pre:'Create form',steps:'1. Upload 200KB PNG logo\n2. Save',expected:'Logo previewed and saved',priority:'High',type:'Positive'},
      {id:'OF-011',name:'Logo upload — SVG accepted; script sanitized',pre:'Create form',steps:'1. Upload SVG with embedded script\n2. Save',expected:'SVG script stripped; stored safely or rejected',priority:'Critical',type:'Security'},
      {id:'OF-012',name:'Logo upload — non-image (PDF) rejected',pre:'Create form',steps:'1. Upload PDF as logo\n2. Save',expected:'Error: image files only',priority:'High',type:'Validation'},
      {id:'OF-013',name:'Logo upload — oversized file (>5MB) rejected',pre:'Create form',steps:'1. Upload 10MB image\n2. Save',expected:'Error: file too large',priority:'High',type:'Validation'},
      {id:'OF-014',name:'Contact email format validated',pre:'Create form',steps:'1. Enter "notanemail" in contact email\n2. Save',expected:'Validation error: invalid email format',priority:'High',type:'Validation'},
      {id:'OF-015',name:'Edit org — change name saves and reflects everywhere',pre:'Org exists; on edit page',steps:'1. Change name to "Acme International"\n2. Save\n3. Check list and detail header',expected:'Name updated in all places',priority:'High',type:'Positive'},
      {id:'OF-016',name:'Edit org — clear name field fails validation',pre:'Edit form',steps:'1. Clear name\n2. Save',expected:'Required field error',priority:'High',type:'Validation'},
      {id:'OF-017',name:'Edit org — change status to Inactive',pre:'Active org; edit form',steps:'1. Set status to Inactive\n2. Save',expected:'Org marked inactive; status badge updates',priority:'High',type:'Positive'},
      {id:'OF-018',name:'Edit org — replace logo with new image',pre:'Org with logo',steps:'1. Upload new logo image\n2. Save',expected:'New logo replaces old immediately',priority:'Medium',type:'Positive'},
      {id:'OF-019',name:'Unsaved edit changes prompt on navigation away',pre:'Edit form; changed name but not saved',steps:'1. Click another sidebar link',expected:'"Unsaved changes" dialog with Leave/Stay options',priority:'High',type:'UI/UX'},
      {id:'OF-020',name:'IDOR — org_admin cannot create org via API',pre:'Logged in as org_admin',steps:'1. POST /api/.../organisations/ with org_admin token',expected:'403 Forbidden; org not created',priority:'Critical',type:'Security'},
    ]
  },
  {
    code:'ORGS-MEMBERS',title:'Organisations — Members Tab',cases:[
      {id:'OM-001',name:'Members tab shows all users across org with role and division',pre:'Org detail open; org has members',steps:'1. Click Members tab on org detail',expected:'Table: name, email, role, division, status, last active, joined date',priority:'Critical',type:'Positive'},
      {id:'OM-002',name:'Search members by email',pre:'Members tab; multiple users',steps:'1. Enter email in search\n2. Observe',expected:'Matching users shown',priority:'High',type:'Positive'},
      {id:'OM-003',name:'Filter members by role',pre:'Members tab; mixed roles',steps:'1. Select role filter "instructor"',expected:'Only instructors listed',priority:'High',type:'Positive'},
      {id:'OM-004',name:'Filter members by division',pre:'Members in multiple divisions',steps:'1. Select division filter',expected:'Only that division\'s members shown',priority:'High',type:'Positive'},
      {id:'OM-005',name:'Filter members by status — Active/Inactive',pre:'Members tab',steps:'1. Select "Active" filter',expected:'Only active members listed',priority:'Medium',type:'Positive'},
      {id:'OM-006',name:'Sort members by name A-Z',pre:'Members tab',steps:'1. Click Name column header',expected:'Alphabetical order',priority:'Low',type:'Positive'},
      {id:'OM-007',name:'Add member to org — invite existing user',pre:'Members tab; user not in org',steps:'1. Click "Add Member"\n2. Search user by email\n3. Select role\n4. Assign to division\n5. Confirm',expected:'User added to org with selected role and division',priority:'High',type:'Positive'},
      {id:'OM-008',name:'Add member — user already in org rejected',pre:'User is already org member',steps:'1. Try to add same user\n2. Confirm',expected:'Error: "User is already a member of this organisation"',priority:'High',type:'Validation'},
      {id:'OM-009',name:'Add member without selecting role fails',pre:'Add member dialog',steps:'1. Select user\n2. Leave role unselected\n3. Confirm',expected:'Required field error on role',priority:'High',type:'Validation'},
      {id:'OM-010',name:'Change member role within org',pre:'Member with instructor role',steps:'1. Click edit on member\n2. Change role to div_admin\n3. Save',expected:'Role updated; member gets new permissions on next action',priority:'High',type:'Positive'},
      {id:'OM-011',name:'Remove member from org with confirmation',pre:'Member exists',steps:'1. Click Remove on member\n2. Confirm dialog',expected:'Member removed from org; loses access to org resources',priority:'High',type:'Positive'},
      {id:'OM-012',name:'Cannot remove the sole org_admin from org',pre:'Org has only one admin',steps:'1. Try to remove the only org_admin',expected:'Error: "Cannot remove the only administrator. Assign another admin first."',priority:'High',type:'Negative'},
      {id:'OM-013',name:'Bulk remove selected members',pre:'Multiple members selected',steps:'1. Check 3 members\n2. Bulk Remove\n3. Confirm',expected:'3 members removed; success toast with count',priority:'Medium',type:'Positive'},
      {id:'OM-014',name:'Export members list as CSV',pre:'Members tab',steps:'1. Click Export\n2. Download CSV',expected:'CSV with name, email, role, division, status, joined date',priority:'High',type:'Positive'},
      {id:'OM-015',name:'Pagination on members list',pre:'More members than page size',steps:'1. Click Next page',expected:'Next set of members loads',priority:'Medium',type:'Positive'},
      {id:'OM-016',name:'Members count in tab header is accurate',pre:'Org with 50 members',steps:'1. View Members tab header',expected:'"50 Members" or "Total: 50" shown accurately',priority:'Medium',type:'Positive'},
      {id:'OM-017',name:'Org_admin can manage only own org members',pre:'Logged in as org_admin',steps:'1. Open Members tab on own org\n2. Try to access another org\'s members via API',expected:'Own org: full access. Other org: 403 Forbidden',priority:'Critical',type:'Security'},
      {id:'OM-018',name:'Invite new user directly from Members tab',pre:'Members tab; + Invite button',steps:'1. Click Invite New User\n2. Enter email, role\n3. Send',expected:'Invitation sent; user appears as Pending in members list',priority:'High',type:'Positive'},
    ]
  },
  {
    code:'ORGS-COURSES',title:'Organisations — Courses Tab',cases:[
      {id:'OC-001',name:'Courses tab shows all courses within the org',pre:'Org detail; org has courses',steps:'1. Click Courses tab on org detail',expected:'List of courses with title, status, instructor, learner count, created date',priority:'High',type:'Positive'},
      {id:'OC-002',name:'Filter org courses by status',pre:'Courses tab; mixed status',steps:'1. Select "Published" filter',expected:'Only published courses in this org shown',priority:'High',type:'Positive'},
      {id:'OC-003',name:'Search org courses by title',pre:'Courses tab',steps:'1. Enter course title in search',expected:'Matching courses shown',priority:'High',type:'Positive'},
      {id:'OC-004',name:'Click course navigates to course detail page',pre:'Course in list',steps:'1. Click course name',expected:'Opens course detail editor for that course',priority:'High',type:'Positive'},
      {id:'OC-005',name:'Create new course from org courses tab',pre:'Courses tab; Create button visible',steps:'1. Click "Create Course"\n2. Fill form\n3. Save',expected:'Course created and associated with this org; appears in org courses list',priority:'High',type:'Positive'},
      {id:'OC-006',name:'Total learners enrolled across org courses shown',pre:'Courses tab',steps:'1. View summary or header area',expected:'Total learner count across all org courses shown',priority:'Medium',type:'Positive'},
      {id:'OC-007',name:'Org_admin sees only own org\'s courses',pre:'Logged in as org_admin',steps:'1. View Courses tab on own org',expected:'Only courses belonging to own org visible; no cross-org courses',priority:'Critical',type:'Security'},
      {id:'OC-008',name:'Empty state when org has no courses',pre:'New org with no courses',steps:'1. Open Courses tab',expected:'"No courses yet" with Create button',priority:'Low',type:'Negative'},
    ]
  },
  {
    code:'ORGS-STNG',title:'Organisations — Settings & Analytics',cases:[
      {id:'OS-001',name:'Org Settings tab loads all configuration options',pre:'Org detail; Settings tab',steps:'1. Click Settings tab',expected:'Sections: Branding, Notifications, Domain, Data Retention, Plan/Quota visible',priority:'High',type:'Positive'},
      {id:'OS-002',name:'Org-level branding — upload banner image',pre:'Org settings',steps:'1. Upload banner image\n2. Save',expected:'Banner shown on org-specific learner portal header',priority:'Medium',type:'Positive'},
      {id:'OS-003',name:'Org-level primary color overrides platform default',pre:'Org settings; brand color field',steps:'1. Enter hex #E63946\n2. Save',expected:'Org\'s learner portal uses org brand color',priority:'Medium',type:'Positive'},
      {id:'OS-004',name:'Org notification email — configure recipient',pre:'Org settings',steps:'1. Set org notification email "orgadmin@acme.com"\n2. Save',expected:'Org-level notifications go to this email',priority:'High',type:'Positive'},
      {id:'OS-005',name:'Org notification email — invalid format rejected',pre:'Org settings',steps:'1. Enter "badformat"\n2. Save',expected:'Validation error: invalid email',priority:'High',type:'Validation'},
      {id:'OS-006',name:'Custom domain per org configured',pre:'Org settings; domain field',steps:'1. Enter "learn.acme.com"\n2. Verify DNS\n3. Save',expected:'Org accessible at custom subdomain',priority:'Medium',type:'Positive'},
      {id:'OS-007',name:'Org quota — user limit shown and editable by super_admin',pre:'Super_admin on org settings',steps:'1. Change user limit to 200\n2. Save',expected:'Org can have up to 200 active users; enforcement kicks in on 201st',priority:'High',type:'Positive'},
      {id:'OS-008',name:'Org quota — course limit configurable',pre:'Org settings',steps:'1. Set course limit to 50\n2. Save',expected:'Org limited to 50 courses; creation blocked at limit',priority:'High',type:'Positive'},
      {id:'OS-009',name:'Analytics tab — org-level user growth chart',pre:'Org detail; Analytics tab',steps:'1. Click Analytics tab',expected:'Chart showing new users added per week/month over time',priority:'High',type:'Positive'},
      {id:'OS-010',name:'Analytics tab — course completion rate for org',pre:'Analytics tab; learner activity exists',steps:'1. View completion metrics',expected:'Average completion rate across all org courses displayed',priority:'High',type:'Positive'},
      {id:'OS-011',name:'Analytics tab — active learners count',pre:'Analytics tab',steps:'1. View active learners metric',expected:'Count of learners who accessed content in last 30 days',priority:'Medium',type:'Positive'},
      {id:'OS-012',name:'Analytics tab — date range filter changes metrics',pre:'Analytics tab',steps:'1. Change from "All Time" to "Last 30 Days"',expected:'All metrics update to reflect selected period',priority:'Medium',type:'Positive'},
      {id:'OS-013',name:'Analytics tab — export org report as CSV',pre:'Analytics tab',steps:'1. Click Export\n2. Download CSV',expected:'CSV with org-level summary data',priority:'Medium',type:'Positive'},
      {id:'OS-014',name:'Org_admin cannot edit quota settings',pre:'Logged in as org_admin on org settings',steps:'1. Try to change user quota\n2. Save',expected:'Quota fields read-only for org_admin; only super_admin can edit',priority:'Critical',type:'Security'},
    ]
  },
];
