import { test, expect } from '@playwright/test';

test('Log in and Dashboard Checks', async ({ page }) => {
  await page.goto('https://admin.dev.budgetnista-admin.qilinlab.com/login');
  await page.getByRole('textbox', { name: 'admin@gmail.com' }).fill('superadmin@yopmail.com');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('Admin@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL(/(?!.*login)/, { timeout: 15000 });
  await expect(page.getByRole('heading', { name: 'Analytics' })).toBeVisible();
  await page.getByRole('link', { name: 'Organizations' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Organizations' })).toBeVisible();
  await page.getByRole('link', { name: 'Divisions & Access' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Divisions & Access' })).toBeVisible();
  await page.getByRole('link', { name: 'Users' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Users' })).toBeVisible();
  await page.getByRole('link', { name: 'Invitees' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Invitees' })).toBeVisible();
  await page.getByRole('link', { name: 'Courses' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Courses' })).toBeVisible();
  await page.getByRole('link', { name: 'Media library' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Media library' })).toBeVisible();
  await page.getByRole('link', { name: 'Instructors' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Instructors' })).toBeVisible();
  await page.getByRole('link', { name: 'Bundles' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Bundles' })).toBeVisible();
  await page.getByRole('link', { name: 'Module Library' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Module Library' })).toBeVisible();
  await page.getByRole('link', { name: 'Pathways' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Pathways' })).toBeVisible();
  await page.getByRole('link', { name: 'Forums' }).click();
  await expect(page.getByRole('heading', { name: 'Forums' })).toBeVisible();
  await page.getByRole('link', { name: 'Moderation' }).click();
  await expect(page.getByRole('heading', { name: 'Moderation', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Rewards' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Rewards' })).toBeVisible();
  await page.getByRole('link', { name: 'Products' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Products' })).toBeVisible();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Transactions' })).toBeVisible();
  await page.getByRole('link', { name: 'Billing' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Billing' })).toBeVisible();
  await page.getByRole('link', { name: 'Settings' }).click();
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible();
  await page.getByLabel('Primary').getByRole('link', { name: 'Notifications' }).click();
  await expect(page.getByRole('banner').getByRole('heading', { name: 'Notifications' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
});